name: Rust
permissions:
  contents: read

on:
  push:
    branches: [ "master", "main", "develop"]
  pull_request:
    branches: [ "master", "main", "develop" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  berger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Install minimal toolchain
      - name: Install minimal stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-berger for full suite testing
        run: cargo install --git https://github.com/RustyNova016/cargo-berger --rev 5a56c3dae289b142885705c97e886a0c6f5c4a48

      - name: Install cargo-hack
        run: cargo +stable install cargo-hack --locked

      - name: Install cargo-msrv
        run: cargo install cargo-msrv --all-features

      - name: Install cargo-machete
        run: cargo install cargo-machete --locked

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      # - name: Install cargo-minimal-versions
      #   run: cargo +stable install cargo-minimal-versions --locked

      - name: Run berger ci
        run: cargo-berger rust ci